services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./client/src:/app/src
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./patterns:/app/patterns
    environment:
      - NODE_ENV=development
      - BETTER_AUTH_URL=http://localhost:3000
    depends_on:
      - db
